<?php

namespace ContainerYTzH5GU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getErrorControllerService extends Apps_RestApi_KernelDevDebugContainer
{
    /**
     * Gets the public 'Apps\RestApi\Modules\Common\Controllers\ErrorController' shared autowired service.
     *
     * @return \Apps\RestApi\Modules\Common\Controllers\ErrorController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/Modules/Common/Controllers/ErrorController.php';

        $container->services['Apps\\RestApi\\Modules\\Common\\Controllers\\ErrorController'] = $instance = new \Apps\RestApi\Modules\Common\Controllers\ErrorController();

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('Apps\\RestApi\\Modules\\Common\\Controllers\\ErrorController', $container));

        return $instance;
    }
}
